#!/usr/bin/env python3
"""Plot measured circuit response and host-rate alias consistency datasets.

Requires matplotlib. Inputs are generated by SeptumAnalogOutputTests and
SeptumAnalyzeFidelity; this script does not alter or normalize measurements.
"""
import argparse
import csv
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def save(fig, directory, name):
    for extension in ("png", "svg"):
        destination = directory / f"{name}.{extension}"
        fig.savefig(destination, dpi=160,
                    facecolor="white", bbox_inches="tight")
        if extension == "svg":
            destination.write_text("\n".join(
                line.rstrip() for line in destination.read_text(encoding="utf-8").splitlines()
            ) + "\n", encoding="utf-8")
    plt.close(fig)


def circuit_plot(path, directory):
    with path.open() as source:
        rows = [{key: float(value) for key, value in row.items()}
                for row in csv.DictReader(source)]
    fig, axes = plt.subplots(2, 1, figsize=(10, 7.2), sharex=True)
    rates = sorted({row["sample_rate_hz"] for row in rows})
    colors = ("#ca573f", "#338ba5", "#6a5796", "#56814f")
    for rate, color in zip(rates, colors):
        selected = [row for row in rows if row["sample_rate_hz"] == rate]
        frequencies = [row["frequency_hz"] for row in selected]
        axes[0].semilogx(frequencies, [row["magnitude_error_db"] for row in selected],
                        color=color, label=f"{rate / 1000:g} kHz")
        axes[1].semilogx(frequencies, [row["phase_error_deg"] for row in selected], color=color)
    for axis in axes:
        axis.axhline(0, color="#777777", linewidth=0.7)
        axis.grid(alpha=0.17, which="both")
        axis.spines[["top", "right"]].set_visible(False)
    axes[0].set_ylabel("Magnitude error (dB)")
    axes[0].legend(frameon=False, ncol=4, loc="lower left")
    axes[1].set_ylabel("Phase error (degrees)")
    axes[1].set_xlabel("Frequency (Hz)")
    axes[1].set_xlim(20, 20000)
    fig.suptitle("Output circuit: measured error against the schematic model",
                 fontsize=16, fontweight="bold", x=0.1, ha="left")
    fig.text(0.1, 0.92, "8× bilinear circuit simulation · 74-sample transport delay removed",
             fontsize=11, color="#555555")
    fig.text(0.1, 0.015, "Reference: independent nodal analysis of Roland's component network; not a hardware recording.",
             fontsize=10, color="#555555")
    fig.tight_layout(rect=(0, 0.045, 1, 0.91))
    save(fig, directory, "output-circuit-error")


def load_alias(path):
    with (path / "summary.tsv").open() as source:
        return {(int(row["rate"]), row["metric"]): float(row["value"])
                for row in csv.DictReader(source, delimiter="\t")
                if row["fixture"] == "supersaw-n93-spread0"
                and row["metric"] in ("probe_15940_dbc", "probe_19840_dbc")}


def rate_plot(native, reference, directory):
    datasets = (load_alias(native), load_alias(reference))
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.8), sharey=True)
    for axis, data, title in zip(axes, datasets, ("Native engine", "Fixed-rate prototype")):
        rates = sorted({rate for rate, _ in data})
        for metric, label, color in (("probe_15940_dbc", "15,940 Hz", "#ca573f"),
                                     ("probe_19840_dbc", "19,840 Hz", "#338ba5")):
            axis.plot(range(len(rates)), [data[(rate, metric)] for rate in rates],
                      "o-", color=color, label=label, linewidth=2, markersize=6)
        axis.set_xticks(range(len(rates)), [f"{rate / 1000:g}" for rate in rates])
        axis.set_xlabel("Host sample rate (kHz)")
        axis.set_title(title, loc="left", fontsize=13, fontweight="bold")
        axis.grid(axis="y", alpha=0.17)
        axis.spines[["top", "right"]].set_visible(False)
        axis.legend(frameon=False, loc="lower left")
    axes[0].set_ylabel("Level relative to fundamental (dBc)")
    fig.suptitle("A6 Super Saw: host-dependent aliasing", fontsize=16,
                 fontweight="bold", x=0.08, ha="left")
    fig.text(0.08, 0.025, "Same raw patch and MIDI · prototype uses a provisional 44.1 kHz core · consistency is not hardware equivalence",
             fontsize=9, color="#555555")
    fig.tight_layout(rect=(0, 0.06, 1, 0.9))
    save(fig, directory, "rate-consistency")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--circuit", type=Path)
    parser.add_argument("--native", type=Path)
    parser.add_argument("--reference", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 11,
                         "svg.fonttype": "none", "axes.labelpad": 8})
    if not args.circuit and not (args.native and args.reference):
        parser.error("provide --circuit or both --native and --reference")
    args.output.mkdir(parents=True, exist_ok=True)
    if args.circuit:
        circuit_plot(args.circuit, args.output)
    if args.native and args.reference:
        rate_plot(args.native, args.reference, args.output)


if __name__ == "__main__":
    main()
